export const bookMap = [
  { name: "창세기", chapters: 50, short: "창" },
  { name: "출애굽기", chapters: 40, short: "출" },
  { name: "레위기", chapters: 27, short: "레" },
  { name: "민수기", chapters: 36, short: "민" },
  { name: "신명기", chapters: 34, short: "신" },
  { name: "여호수아", chapters: 24, short: "수" },
  { name: "사사기", chapters: 21, short: "삿" },
  { name: "룻기", chapters: 4, short: "룻" },
  { name: "사무엘상", chapters: 31, short: "삼상" },
  { name: "사무엘하", chapters: 24, short: "삼하" },
  { name: "열왕기상", chapters: 22, short: "왕상" },
  { name: "열왕기하", chapters: 25, short: "왕하" },
  { name: "역대상", chapters: 29, short: "대상" },
  { name: "역대하", chapters: 36, short: "대하" },
  { name: "에스라", chapters: 10, short: "스" },
  { name: "느혜미야", chapters: 13, short: "느" },
  { name: "에스더", chapters: 10, short: "에" },
  { name: "욥기", chapters: 42, short: "욥" },
  { name: "시편", chapters: 150, short: "시" },
  { name: "잠언", chapters: 31, short: "잠" },
  { name: "전도서", chapters: 12, short: "전" },
  { name: "아가", chapters: 8, short: "아" },
  { name: "이사야", chapters: 66, short: "사" },
  { name: "예레미야", chapters: 52, short: "렘" },
  { name: "예레미야애가", chapters: 5, short: "애" },
  { name: "에스겔", chapters: 48, short: "겔" },
  { name: "다니엘", chapters: 12, short: "단" },
  { name: "호세아", chapters: 14, short: "호" },
  { name: "요엘", chapters: 3, short: "욜" },
  { name: "아모스", chapters: 9, short: "암" },
  { name: "오바댜", chapters: 1, short: "옵" },
  { name: "요나", chapters: 4, short: "욘" },
  { name: "미가", chapters: 7, short: "미" },
  { name: "나훔", chapters: 3, short: "나" },
  { name: "하박국", chapters: 3, short: "합" },
  { name: "스바냐", chapters: 3, short: "습" },
  { name: "학개", chapters: 2, short: "학" },
  { name: "스가랴", chapters: 14, short: "슥" },
  { name: "말라기", chapters: 4, short: "말" },
  { name: "마태복음", chapters: 28, short: "마" },
  { name: "마가복음", chapters: 16, short: "막" },
  { name: "누가복음", chapters: 24, short: "눅" },
  { name: "요한복음", chapters: 21, short: "요" },
  { name: "사도행전", chapters: 28, short: "행" },
  { name: "로마서", chapters: 16, short: "롬" },
  { name: "고린도전서", chapters: 16, short: "고전" },
  { name: "고린도후서", chapters: 13, short: "고후" },
  { name: "갈라디아서", chapters: 6, short: "갈" },
  { name: "에베소서", chapters: 6, short: "엡" },
  { name: "빌립보서", chapters: 4, short: "빌" },
  { name: "골로새서", chapters: 4, short: "골" },
  { name: "데살로니가전서", chapters: 5, short: "살전" },
  { name: "데살로니가후서", chapters: 3, short: "살후" },
  { name: "디모데전서", chapters: 6, short: "딤전" },
  { name: "디모데후서", chapters: 4, short: "딤후" },
  { name: "디도서", chapters: 3, short: "딛" },
  { name: "빌레몬서", chapters: 1, short: "몬" },
  { name: "히브리서", chapters: 13, short: "히" },
  { name: "야고보서", chapters: 5, short: "약" },
  { name: "베드로전서", chapters: 5, short: "벧전" },
  { name: "베드로후서", chapters: 3, short: "벧후" },
  { name: "요한1서", chapters: 5, short: "요일" },
  { name: "요한2서", chapters: 1, short: "요이" },
  { name: "요한3서", chapters: 1, short: "요삼" },
  { name: "유다서", chapters: 1, short: "유" },
  { name: "요한계시록", chapters: 22, short: "계" },
];

export const bookList = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1Samuel",
  "2Samuel",
  "1Kings",
  "2Kings",
  "1Chronicles",
  "2Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "SongofSolomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1Corinthians",
  "2Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1Thessalonians",
  "2Thessalonians",
  "1Timothy",
  "2Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1Peter",
  "2Peter",
  "1John",
  "2John",
  "3John",
  "Jude",
  "Revelation"
];